import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { FileText, Download, CheckCircle2, ShieldCheck, ChevronRight, FileCheck, Layers } from "lucide-react";

const ReportsSection = () => {
  const [activePage, setActivePage] = useState(1);

  const reportPages = [
    {
      page: 1,
      title: "Executive Summary & ESG Disclosure",
      summary: "High-level overview of corporate carbon footprint, total Scope 1 & 2 aggregated emissions, and key reduction milestones achieved across active monitoring quarters.",
      table: [
        { label: "Total Scope 1 (Direct)", val: "6,120 kg CO₂e", status: "Verified" },
        { label: "Total Scope 2 (Indirect)", val: "10,254 kg CO₂e", status: "Verified" },
        { label: "Gross Corporate Output", val: "16,374 kg CO₂e", status: "100% Complete" },
      ],
    },
    {
      page: 2,
      title: "Scope 1 & 2 Emissions Breakdown",
      summary: "Detailed energy source breakdown comparing grid electricity, natural gas heating loads, and auxiliary fuel generation against regional baseline factors.",
      table: [
        { label: "Grid Electricity (kWh)", val: "14,200 kWh", status: "Scope 2" },
        { label: "Natural Gas (Therms)", val: "450 Therms", status: "Scope 1" },
        { label: "Diesel Generators", val: "120 Gallons", status: "Scope 1" },
      ],
    },
    {
      page: 3,
      title: "Facility Scope & Intensity Index",
      summary: "Facility-level energy density analysis, floor space normalization (kg/sq ft), and peak-demand anomaly log across monitored operational sites.",
      table: [
        { label: "San Francisco HQ", val: "5,420 kg (0.12 kg/sq ft)", status: "Optimal" },
        { label: "Austin Ops Hub", val: "6,810 kg (0.10 kg/sq ft)", status: "Optimal" },
        { label: "Chicago Hub", val: "4,144 kg (0.14 kg/sq ft)", status: "Alert Peak" },
      ],
    },
    {
      page: 4,
      title: "Decarbonization Roadmap & Actions",
      summary: "Actionable recommendations generated by Gemini AI, targeting HVAC setback schedules, tariff optimizations, and off-hour load shedding.",
      table: [
        { label: "HVAC Schedule Setback", val: "Est -850 kg CO₂e/yr", status: "Recommended" },
        { label: "Tariff Peak Shaving", val: "Est $2,400 Savings", status: "High Priority" },
        { label: "Solar PPA Evaluation", val: "Scope 2 Reduction", status: "Long Term" },
      ],
    },
    {
      page: 5,
      title: "Audit Trail & Verification Appendix",
      summary: "Complete line-item audit trail logging OCR invoice timestamps, source document IDs, regional grid emission factors, and verification metadata.",
      table: [
        { label: "OCR Document Hash", val: "sha256:e9f...8a12", status: "Immutable" },
        { label: "Emission Factor Standard", val: "EPA eGRID 2024", status: "Verified" },
        { label: "Verification Status", val: "Zero Discrepancy", status: "Audit-Ready" },
      ],
    },
  ];

  return (
    <section id="reports" className="py-16 sm:py-24 bg-[#E4E5DB]/30 border-b border-[#DDDDD0]">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* SECTION HEADER */}
        <div className="text-center max-w-3xl mx-auto mb-14 space-y-3">
          <span className="text-xs font-extrabold text-[#2F5241] uppercase tracking-wider block font-heading">
            Executive Compliance Documentation
          </span>
          <h2 className="text-2xl sm:text-4xl font-extrabold text-[#152A38] tracking-tight font-heading">
            14-Section Audit-Ready ESG Report Preview
          </h2>
          <p className="text-xs sm:text-sm text-[#7A8597] font-medium leading-relaxed">
            Every EcoAudit workspace generates comprehensive sustainability documentation formatted for executive boards, compliance rating agencies, and third-party auditors.
          </p>
        </div>

        {/* INTERACTIVE REPORT PREVIEW CONTAINER */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start max-w-5xl mx-auto">
          
          {/* PAGE SELECTOR NAVIGATION */}
          <div className="lg:col-span-4 space-y-2 text-left">
            <span className="text-[10px] font-extrabold text-[#7A8597] uppercase tracking-wider block mb-2 px-1">
              Select Document Section
            </span>
            {reportPages.map((p) => (
              <button
                key={p.page}
                onClick={() => setActivePage(p.page)}
                className={`w-full p-3.5 rounded-2xl border text-left transition-all cursor-pointer flex items-center justify-between ${
                  activePage === p.page
                    ? "bg-[#152A38] text-[#E4E5DB] border-[#2F5241] shadow-md"
                    : "bg-[#F7F6EE] text-[#152A38] border-[#DDDDD0] hover:bg-[#EEEDDF]"
                }`}
              >
                <div>
                  <span className="text-[10px] font-extrabold block uppercase tracking-wide opacity-75">
                    Section 0{p.page}
                  </span>
                  <span className="text-xs font-extrabold block font-heading truncate">
                    {p.title}
                  </span>
                </div>
                <ChevronRight className={`w-4 h-4 shrink-0 ${activePage === p.page ? "text-emerald-400" : "text-[#7A8597]"}`} />
              </button>
            ))}

            <div className="pt-4">
              <div className="bg-[#EEEDDF] p-4 rounded-2xl border border-[#DDDDD0] space-y-2">
                <div className="flex items-center gap-2 text-[#2F5241] text-xs font-extrabold">
                  <FileCheck className="w-4 h-4" />
                  <span>One-Click PDF Export</span>
                </div>
                <p className="text-[11px] font-medium text-[#7A8597] leading-relaxed">
                  Generated reports include embedded charts, facility tables, and verified GHG audit trail hashes.
                </p>
              </div>
            </div>
          </div>

          {/* REPORT DOCUMENT CANVAS */}
          <div className="lg:col-span-8">
            <AnimatePresence mode="wait">
              <motion.div
                key={activePage}
                initial={{ opacity: 0, scale: 0.98 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.98 }}
                transition={{ duration: 0.25 }}
                className="bg-white rounded-[28px] p-6 sm:p-8 border border-[#DDDDD0] shadow-xl text-left space-y-5 relative"
              >
                {/* WATERMARK BADGE */}
                <div className="flex items-center justify-between pb-4 border-b border-[#DDDDD0]">
                  <div className="flex items-center gap-2.5">
                    <div className="w-7 h-7 rounded-lg bg-[#152A38] text-emerald-400 flex items-center justify-center text-xs font-extrabold">
                      EA
                    </div>
                    <div>
                      <span className="text-xs font-extrabold text-[#152A38] block leading-none font-heading">
                        EcoAudit AI Executive ESG Report
                      </span>
                      <span className="text-[9.5px] font-bold text-[#7A8597] block mt-0.5">
                        Corporate Compliance Standard • Page 0{activePage} of 14
                      </span>
                    </div>
                  </div>

                  <span className="px-3 py-1 rounded-full bg-emerald-50 text-emerald-700 text-[10px] font-extrabold border border-emerald-200">
                    Audit Verified
                  </span>
                </div>

                {/* PAGE TITLE & SUMMARY */}
                <div className="space-y-2">
                  <h4 className="text-base sm:text-lg font-extrabold text-[#152A38] font-heading">
                    {reportPages[activePage - 1].title}
                  </h4>
                  <p className="text-xs text-[#7A8597] font-medium leading-relaxed">
                    {reportPages[activePage - 1].summary}
                  </p>
                </div>

                {/* SAMPLE DATA TABLE */}
                <div className="bg-[#F7F6EE] rounded-2xl border border-[#DDDDD0] overflow-hidden">
                  <table className="w-full text-left text-xs">
                    <thead className="bg-[#EEEDDF] text-[10px] font-extrabold text-[#7A8597] uppercase tracking-wider border-b border-[#DDDDD0]">
                      <tr>
                        <th className="p-3">Disclosure Metric</th>
                        <th className="p-3">Aggregated Value</th>
                        <th className="p-3">Compliance Status</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-[#DDDDD0]/70 font-semibold text-[#152A38]">
                      {reportPages[activePage - 1].table.map((row, idx) => (
                        <tr key={idx} className="hover:bg-[#EEEDDF]/50 transition-colors">
                          <td className="p-3">{row.label}</td>
                          <td className="p-3 text-[#2F5241] font-extrabold">{row.val}</td>
                          <td className="p-3">
                            <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-emerald-100 text-emerald-800">
                              {row.status}
                            </span>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>

                {/* FOOTER OF REPORT PREVIEW */}
                <div className="pt-4 border-t border-[#DDDDD0] flex items-center justify-between text-[10px] text-[#7A8597] font-bold">
                  <span>Confidential • Prepared for Corporate Stakeholders</span>
                  <span>ISO 14064 / GHG Protocol Aligned</span>
                </div>

              </motion.div>
            </AnimatePresence>
          </div>

        </div>

      </div>
    </section>
  );
};

export default ReportsSection;
